CATFLOW Geospatial Tool
VForWaTer/tool_whiteboxgis pull request #10
Opened 2023-05-03 10:24 UTC by Ash-Manoj

Restructured the run.py for generating required Raster files for CATFLOW Hillslope Wizard using a single Tool.

2023-06-05 07:03 UTC, mmaelicke requested changes
Nice work @Ash-Manoj ! Sorry for my late response, I forgot about this pull request. There are some minor changes requested.

2023-06-05 07:03 UTC, mmaelicke commented on src/tool.yml
> -        default: None
This parameter does not have a default, but is optional, as the tool will set it to 100. The difference between optional and default is a bit confusing. You can add `optional: true` here and add to the description that the threshold is always 100, but you can overwrite this constant

2023-06-15 07:09 UTC, mmaelicke commented
Any progress on this?

2023-06-15 08:57 UTC, Ash-Manoj commented
> Any progress on this?

2023-06-15 08:58 UTC, Ash-Manoj commented
Working on the changes. Should be able to push by next week.

2023-06-23 11:04 UTC, Ash-Manoj commented on src/run.py
> +elif toolname == 'catflow_hillslope_generator':
Agreed. Changed to hillslope_generator.

2023-06-23 11:05 UTC, Ash-Manoj commented on src/run.py
> +        shp = kwargs.get('shapefile', '/in/Shapefile.shp')
Changed to Basin

2023-06-23 11:06 UTC, Ash-Manoj commented on src/run.py
> +        thres = kwargs.get('stream_threshold', 100.0)
Discussion on default values for the flow accumulation.

2023-06-23 11:07 UTC, Ash-Manoj commented on src/tool.yml
> +    catflow_hillslope_generator:
Changed

2023-07-25 09:08 UTC, merged